# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIhNhoBEpBew81oLB6NrSVJM0glmfM8V
"""

!pip install ultralytics roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="9UNlFiaevGRzLO9PN2U0")
project = rf.workspace("school-fuhih").project("vietnamese-license-plate-tptd0")
version = project.version(1)
dataset = version.download("yolov8")

!yolo task=detect mode=train data={dataset.location}/data.yaml model=yolov8n.pt epochs=50